### PR TITLE
Extend New-EP with Android profiles

### PR DESCRIPTION
**Pull request by NickETH**
Erweiterung von New-bConnectEndpoint um Android Profile.
Umbenennung von Parameter "GroupGuid" auf "GuidOrgUnit" (Umsetzung der Anpassung im API)

### CODE REVIEW

**Review by T0biii — CHANGES_REQUESTED** [review]
maybe you want to split the new-JobStep (there also some unnecessary "echo" commands) and the New-EP in 2 branches/pr?

**Comment by NickETH** [comment]
You are right.
That was to fast.
It was meant to do it with 2 PR.

**Comment by NickETH** [comment]
i will wait with the other PR until this one is accepted.

**Comment by NickETH** [comment]
Do you need anything else to merge this PR?

**Review by T0biii — APPROVED** [review]
LGTM. so now someone form @baramundisoftware needs to merge it

**Pull request merged**
