### PR TITLE
add functions to work on job steps.

### PR DESCRIPTION
**Pull request by NickETH**
Hi,
another PR. 
Changes:
Invoke-bConnectPatch, needs Depth parameter on ConvertTo-Json
New functions:
New-bConnectJobStep
Edit-bConnectJobSteps

Thanks, Nick

### CODE REVIEW

**Review by T0biii — CHANGES_REQUESTED** [review]
seems a bit off, maybe use spaces?:
image
in both files it looks wired

**Comment by NickETH** [comment]
ok, i can change that. but this is cosmetic...
What do you mean with "wired"?

**Comment by T0biii** [comment]
image
maybe its just me ;)

**Comment by NickETH** [comment]
Ok, i see.
Should use Python behaviour here too, i think...
I correct it.

**Review by T0biii — APPROVED** [review]

**Comment by NickETH** [comment]
@baramundi-ahaugk: Could please merge this PR too?
Thank you.
G, Nick

**Review by baramundi-ahaugk — APPROVED** [review]

**Pull request merged**
